# Generated by Django 5.1.6 on 2025-02-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelexIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('app_name', models.CharField(max_length=255)),
                ('app_description', models.TextField()),
                ('app_url', models.URLField()),
                ('app_logo', models.URLField()),
                ('background_color', models.CharField(max_length=7)),
                ('integration_category', models.CharField(max_length=100)),
                ('integration_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('always_online', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('tick_url', models.URLField()),
                ('target_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='telex_api.telexintegration')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='telex_api.telexintegration')),
            ],
        ),
    ]
